/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.app.distribuidas.viewInventario;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import project.app.distribuidas.model.Articulo;
import project.app.distribuidas.viewLogin.jframe_mainOptions;
import project.app.distribuidas.viewLogin.jframe_signIn;

/**
 *
 * @author pocho
 */
public class jframe_InventarioSimple1 extends javax.swing.JFrame {

    /**
     * Creates new form jframe_simple1
     */
    DefaultTableModel modelo;
    public jframe_InventarioSimple1() {
        initComponents();
        consultar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jp_datos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nomArt = new javax.swing.JTextField();
        txt_precioA = new javax.swing.JTextField();
        jp_acciones = new javax.swing.JPanel();
        btn_agregA = new javax.swing.JButton();
        btn_modifiA = new javax.swing.JButton();
        btn_eliminA = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        jp_listar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Art = new javax.swing.JTable();
        btn_Regresar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        btn_buscarA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ARTÍCULOS");

        jp_datos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio");

        txt_nomArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomArtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_datosLayout = new javax.swing.GroupLayout(jp_datos);
        jp_datos.setLayout(jp_datosLayout);
        jp_datosLayout.setHorizontalGroup(
            jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datosLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_nomArt)
                    .addComponent(txt_precioA, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_datosLayout.setVerticalGroup(
            jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datosLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nomArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_precioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jp_acciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        btn_agregA.setText("Agregar");
        btn_agregA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregAActionPerformed(evt);
            }
        });

        btn_modifiA.setText("Modificar");

        btn_eliminA.setText("Eliminar");

        btn_nuevo.setText("Nuevo");

        javax.swing.GroupLayout jp_accionesLayout = new javax.swing.GroupLayout(jp_acciones);
        jp_acciones.setLayout(jp_accionesLayout);
        jp_accionesLayout.setHorizontalGroup(
            jp_accionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_accionesLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btn_agregA)
                .addGap(37, 37, 37)
                .addComponent(btn_modifiA)
                .addGap(45, 45, 45)
                .addComponent(btn_eliminA)
                .addGap(37, 37, 37)
                .addComponent(btn_nuevo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_accionesLayout.setVerticalGroup(
            jp_accionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_accionesLayout.createSequentialGroup()
                .addGroup(jp_accionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregA)
                    .addComponent(btn_modifiA)
                    .addComponent(btn_eliminA)
                    .addComponent(btn_nuevo))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jp_listar.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado"));

        table_Art.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio"
            }
        ));
        jScrollPane1.setViewportView(table_Art);

        javax.swing.GroupLayout jp_listarLayout = new javax.swing.GroupLayout(jp_listar);
        jp_listar.setLayout(jp_listarLayout);
        jp_listarLayout.setHorizontalGroup(
            jp_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_listarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jp_listarLayout.setVerticalGroup(
            jp_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btn_Regresar.setBackground(new java.awt.Color(51, 153, 0));
        btn_Regresar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Regresar.setText("Regresar");
        btn_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegresarActionPerformed(evt);
            }
        });

        jLabel4.setText("Buscar");

        btn_buscarA.setText("Buscar");
        btn_buscarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jp_datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jp_acciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_listar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 189, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(btn_buscarA)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscarA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_acciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_listar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Regresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregAActionPerformed

    private void txt_nomArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomArtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomArtActionPerformed

    private void btn_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegresarActionPerformed
       jframe_mainOptions mo= new jframe_mainOptions();
        mo.setVisible(true);
        mo.setSize(500,400);
        mo.setResizable(false);
        mo.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_RegresarActionPerformed

    private void btn_buscarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscarAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe_InventarioSimple1().setVisible(true);
            }
        });
    }
    
     public void consultar() 
    {
        String user = "";
        String pass = "";
        String login = user+";"+pass+";/listarArticulos";
        try {
            // CLIENTE UDP 
            Socket cliente = new Socket("localhost",1410);
            ObjectOutputStream mensaje = new ObjectOutputStream(cliente.getOutputStream());
            mensaje.writeObject(login);
            ObjectInputStream recepcion = new ObjectInputStream(cliente.getInputStream());
            ArrayList<Articulo>Arti = (ArrayList<Articulo>) recepcion.readObject();
            
        Object[] articulo = new Object[3];
        modelo = (DefaultTableModel) table_Art.getModel();
        for(int i = 0;i<3;i++)
        {
            articulo [0] = Arti.get(i).getId();
            articulo [1] = Arti.get(i).getNombre();
            articulo [2] = Arti.get(i).getPrecio();
            modelo.addRow(articulo);
        }
        table_Art.setModel(modelo);
           
            cliente.close();
        } catch (IOException ex) {
            Logger.getLogger(jframe_signIn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) { 
           Logger.getLogger(jframe_signIn.class.getName()).log(Level.SEVERE, null, ex);
       } 
        
       
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Regresar;
    private javax.swing.JButton btn_agregA;
    private javax.swing.JButton btn_buscarA;
    private javax.swing.JButton btn_eliminA;
    private javax.swing.JButton btn_modifiA;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jp_acciones;
    private javax.swing.JPanel jp_datos;
    private javax.swing.JPanel jp_listar;
    private javax.swing.JTable table_Art;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_nomArt;
    private javax.swing.JTextField txt_precioA;
    // End of variables declaration//GEN-END:variables
}
