SELECT * FROM lgh.usuarios;


SELECT NUMERO_CABECERA_FACTU,FECHA_CABECERA_FACTU,NOMBRE_CIU
FROM cabecera_factura cf,cliente c,ciudad ciu
WHERE c.CODIGO_CLI = cf.CODIGO_CLI AND c.CODIGO_CIU = ciu.CODIGO_CIU AND c.RUC_CLI = '1726525155'